name: BDcpvper
version: ${version}
main: com.zymekoh.bdcpvper.Main
api-version: "1.21"
author: Zymekoh
description: Improves Bedrock Crystal PvP with Floodgate while keeping Java behavior intact.
depend: [floodgate]
permissions:
  bdcpvper.use:
    description: Allows use of plugin features.
    default: true
  bdcpvper.notify:
    description: Allows receiving Bedrock notifications.
    default: op
